<?php

namespace Database\Seeders;

use App\Models\ParentModel;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class ParentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $parents = [
            [
                'first_name' => 'Michael',
                'middle_name' => 'James',
                'last_name' => 'Anderson',
                'date_of_birth' => '1980-03-15',
                'gender' => 'M',
                'nationality' => 'American',
                'occupation' => 'Software Engineer',
                'workplace' => 'TechCorp Inc.',
                'relationship_type' => 'Father',
                'is_emergency_contact' => true,
                'address_line1' => '123 Oak Street',
                'address_line2' => 'Apt 4B',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62701',
                'country' => 'USA',
                'home_phone' => '+1-217-555-0101',
                'mobile_phone' => '+1-217-555-0102',
                'work_phone' => '+1-217-555-0103',
                'email' => 'michael.anderson@email.com',
            ],
            [
                'first_name' => 'Sarah',
                'middle_name' => 'Elizabeth',
                'last_name' => 'Johnson',
                'date_of_birth' => '1982-07-22',
                'gender' => 'F',
                'nationality' => 'American',
                'occupation' => 'Teacher',
                'workplace' => 'Springfield Elementary',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '456 Maple Avenue',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62702',
                'country' => 'USA',
                'home_phone' => '+1-217-555-0201',
                'mobile_phone' => '+1-217-555-0202',
                'email' => 'sarah.johnson@email.com',
            ],
            [
                'first_name' => 'David',
                'middle_name' => 'Robert',
                'last_name' => 'Williams',
                'date_of_birth' => '1978-11-08',
                'gender' => 'M',
                'nationality' => 'American',
                'occupation' => 'Doctor',
                'workplace' => 'Springfield Medical Center',
                'relationship_type' => 'Father',
                'is_emergency_contact' => false,
                'address_line1' => '789 Pine Street',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62703',
                'country' => 'USA',
                'home_phone' => '+1-217-555-0301',
                'mobile_phone' => '+1-217-555-0302',
                'work_phone' => '+1-217-555-0303',
                'email' => 'david.williams@email.com',
            ],
            [
                'first_name' => 'Jennifer',
                'middle_name' => 'Marie',
                'last_name' => 'Brown',
                'date_of_birth' => '1983-05-14',
                'gender' => 'F',
                'nationality' => 'American',
                'occupation' => 'Nurse',
                'workplace' => 'Springfield Hospital',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '321 Cedar Lane',
                'address_line2' => 'Unit 12',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62704',
                'country' => 'USA',
                'home_phone' => '+1-217-555-0401',
                'mobile_phone' => '+1-217-555-0402',
                'email' => 'jennifer.brown@email.com',
            ],
            [
                'first_name' => 'Robert',
                'middle_name' => 'William',
                'last_name' => 'Davis',
                'date_of_birth' => '1975-09-30',
                'gender' => 'M',
                'nationality' => 'American',
                'occupation' => 'Accountant',
                'workplace' => 'Davis & Associates',
                'relationship_type' => 'Father',
                'is_emergency_contact' => true,
                'address_line1' => '654 Elm Street',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62705',
                'country' => 'USA',
                'home_phone' => '+1-217-555-0501',
                'mobile_phone' => '+1-217-555-0502',
                'work_phone' => '+1-217-555-0503',
                'email' => 'robert.davis@email.com',
            ],
            [
                'first_name' => 'Lisa',
                'middle_name' => 'Ann',
                'last_name' => 'Miller',
                'date_of_birth' => '1981-12-03',
                'gender' => 'F',
                'nationality' => 'American',
                'occupation' => 'Marketing Manager',
                'workplace' => 'Miller Marketing Group',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => false,
                'address_line1' => '987 Birch Road',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62706',
                'country' => 'USA',
                'home_phone' => '+1-217-555-0601',
                'mobile_phone' => '+1-217-555-0602',
                'email' => 'lisa.miller@email.com',
            ],
            [
                'first_name' => 'Christopher',
                'middle_name' => 'John',
                'last_name' => 'Wilson',
                'date_of_birth' => '1979-04-18',
                'gender' => 'M',
                'nationality' => 'American',
                'occupation' => 'Police Officer',
                'workplace' => 'Springfield Police Department',
                'relationship_type' => 'Father',
                'is_emergency_contact' => true,
                'address_line1' => '147 Spruce Street',
                'address_line2' => 'House 5',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62707',
                'country' => 'USA',
                'home_phone' => '+1-217-555-0701',
                'mobile_phone' => '+1-217-555-0702',
                'work_phone' => '+1-217-555-0703',
                'email' => 'christopher.wilson@email.com',
            ],
            [
                'first_name' => 'Amanda',
                'middle_name' => 'Grace',
                'last_name' => 'Moore',
                'date_of_birth' => '1984-08-25',
                'gender' => 'F',
                'nationality' => 'American',
                'occupation' => 'Graphic Designer',
                'workplace' => 'Creative Solutions LLC',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '258 Walnut Avenue',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62708',
                'country' => 'USA',
                'home_phone' => '+1-217-555-0801',
                'mobile_phone' => '+1-217-555-0802',
                'email' => 'amanda.moore@email.com',
            ],
            [
                'first_name' => 'Kevin',
                'middle_name' => 'Paul',
                'last_name' => 'Taylor',
                'date_of_birth' => '1977-01-12',
                'gender' => 'M',
                'nationality' => 'American',
                'occupation' => 'Construction Manager',
                'workplace' => 'Taylor Construction',
                'relationship_type' => 'Father',
                'is_emergency_contact' => false,
                'address_line1' => '369 Chestnut Drive',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62709',
                'country' => 'USA',
                'home_phone' => '+1-217-555-0901',
                'mobile_phone' => '+1-217-555-0902',
                'work_phone' => '+1-217-555-0903',
                'email' => 'kevin.taylor@email.com',
            ],
            [
                'first_name' => 'Michelle',
                'middle_name' => 'Nicole',
                'last_name' => 'Garcia',
                'date_of_birth' => '1985-06-07',
                'gender' => 'F',
                'nationality' => 'American',
                'occupation' => 'Pharmacist',
                'workplace' => 'Springfield Pharmacy',
                'relationship_type' => 'Mother',
                'is_emergency_contact' => true,
                'address_line1' => '741 Poplar Street',
                'address_line2' => 'Building A',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62710',
                'country' => 'USA',
                'home_phone' => '+1-217-555-1001',
                'mobile_phone' => '+1-217-555-1002',
                'email' => 'michelle.garcia@email.com',
            ],
        ];

        foreach ($parents as $parentData) {
            // Create user account for parent
            $user = User::create([
                'name' => $parentData['first_name'].' '.$parentData['last_name'],
                'email' => $parentData['email'],
                'password' => Hash::make('password123'), // Default password
                'email_verified_at' => now(),
            ]);

            // Assign parent role
            $user->assignRole('Parent');

            // Create parent record
            $parent = ParentModel::create([
                'user_id' => $user->id,
                'parent_code' => ParentModel::generateParentCode(),
                'first_name' => $parentData['first_name'],
                'middle_name' => $parentData['middle_name'],
                'last_name' => $parentData['last_name'],
                'date_of_birth' => $parentData['date_of_birth'],
                'gender' => $parentData['gender'],
                'nationality' => $parentData['nationality'],
                'occupation' => $parentData['occupation'],
                'workplace' => $parentData['workplace'],
                'relationship_type' => $parentData['relationship_type'],
                'is_emergency_contact' => $parentData['is_emergency_contact'],
                'is_active' => true,
                'address_line1' => $parentData['address_line1'],
                'address_line2' => $parentData['address_line2'] ?? null,
                'city' => $parentData['city'],
                'state' => $parentData['state'],
                'postal_code' => $parentData['postal_code'],
                'country' => $parentData['country'],
                'home_phone' => $parentData['home_phone'],
                'mobile_phone' => $parentData['mobile_phone'],
                'work_phone' => $parentData['work_phone'] ?? null,
                'email' => $parentData['email'],
            ]);

            $this->command->info("Created parent: {$parent->full_name} ({$parent->parent_code})");
        }
    }
}
