<?php

namespace Database\Seeders;

use App\Models\SecurityStaff;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class SecurityStaffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $securityStaff = [
            [
                'first_name' => 'James',
                'middle_name' => 'Patrick',
                'last_name' => 'O\'Connor',
                'date_of_birth' => '1985-04-12',
                'gender' => 'M',
                'nationality' => 'American',
                'joining_date' => '2023-01-15',
                'employee_id' => 'EMP-SEC-001',
                'shift' => 'Morning',
                'position' => 'Security Supervisor',
                'address_line1' => '123 Security Lane',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62701',
                'country' => 'USA',
                'home_phone' => '+1-217-555-2101',
                'mobile_phone' => '+1-217-555-2102',
                'email' => 'james.oconnor@school.edu',
            ],
            [
                'first_name' => 'Maria',
                'middle_name' => 'Elena',
                'last_name' => 'Rodriguez',
                'date_of_birth' => '1988-08-22',
                'gender' => 'F',
                'nationality' => 'American',
                'joining_date' => '2023-02-01',
                'employee_id' => 'EMP-SEC-002',
                'shift' => 'Evening',
                'position' => 'Security Guard',
                'address_line1' => '456 Guard Street',
                'address_line2' => 'Apt 3B',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62702',
                'country' => 'USA',
                'home_phone' => '+1-217-555-2201',
                'mobile_phone' => '+1-217-555-2202',
                'email' => 'maria.rodriguez@school.edu',
            ],
            [
                'first_name' => 'Daniel',
                'middle_name' => 'Lee',
                'last_name' => 'Thompson',
                'date_of_birth' => '1982-11-30',
                'gender' => 'M',
                'nationality' => 'American',
                'joining_date' => '2023-03-10',
                'employee_id' => 'EMP-SEC-003',
                'shift' => 'Night',
                'position' => 'Security Guard',
                'address_line1' => '789 Watch Drive',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62703',
                'country' => 'USA',
                'home_phone' => '+1-217-555-2301',
                'mobile_phone' => '+1-217-555-2302',
                'email' => 'daniel.thompson@school.edu',
            ],
            [
                'first_name' => 'Angela',
                'middle_name' => 'Rose',
                'last_name' => 'Washington',
                'date_of_birth' => '1990-01-18',
                'gender' => 'F',
                'nationality' => 'American',
                'joining_date' => '2023-04-05',
                'employee_id' => 'EMP-SEC-004',
                'shift' => 'Morning',
                'position' => 'Security Guard',
                'address_line1' => '321 Safety Boulevard',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62704',
                'country' => 'USA',
                'home_phone' => '+1-217-555-2401',
                'mobile_phone' => '+1-217-555-2402',
                'email' => 'angela.washington@school.edu',
            ],
            [
                'first_name' => 'Marcus',
                'middle_name' => 'Anthony',
                'last_name' => 'Johnson',
                'date_of_birth' => '1987-06-14',
                'gender' => 'M',
                'nationality' => 'American',
                'joining_date' => '2023-05-20',
                'employee_id' => 'EMP-SEC-005',
                'shift' => 'Evening',
                'position' => 'Security Guard',
                'address_line1' => '654 Patrol Road',
                'address_line2' => 'Unit 12',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62705',
                'country' => 'USA',
                'home_phone' => '+1-217-555-2501',
                'mobile_phone' => '+1-217-555-2502',
                'email' => 'marcus.johnson@school.edu',
            ],
            [
                'first_name' => 'Sandra',
                'middle_name' => 'Kay',
                'last_name' => 'Miller',
                'date_of_birth' => '1984-09-07',
                'gender' => 'F',
                'nationality' => 'American',
                'joining_date' => '2023-06-12',
                'employee_id' => 'EMP-SEC-006',
                'shift' => 'Night',
                'position' => 'Security Guard',
                'address_line1' => '987 Monitor Lane',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62706',
                'country' => 'USA',
                'home_phone' => '+1-217-555-2601',
                'mobile_phone' => '+1-217-555-2602',
                'email' => 'sandra.miller@school.edu',
            ],
            [
                'first_name' => 'Robert',
                'middle_name' => 'Charles',
                'last_name' => 'Davis',
                'date_of_birth' => '1986-12-25',
                'gender' => 'M',
                'nationality' => 'American',
                'joining_date' => '2023-07-08',
                'employee_id' => 'EMP-SEC-007',
                'shift' => 'Morning',
                'position' => 'Security Officer',
                'address_line1' => '147 Sentry Street',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62707',
                'country' => 'USA',
                'home_phone' => '+1-217-555-2701',
                'mobile_phone' => '+1-217-555-2702',
                'email' => 'robert.davis@school.edu',
            ],
            [
                'first_name' => 'Carmen',
                'middle_name' => 'Isabella',
                'last_name' => 'Garcia',
                'date_of_birth' => '1989-03-16',
                'gender' => 'F',
                'nationality' => 'American',
                'joining_date' => '2023-08-15',
                'employee_id' => 'EMP-SEC-008',
                'shift' => 'Evening',
                'position' => 'Security Officer',
                'address_line1' => '258 Watchman Way',
                'address_line2' => 'Building C',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62708',
                'country' => 'USA',
                'home_phone' => '+1-217-555-2801',
                'mobile_phone' => '+1-217-555-2802',
                'email' => 'carmen.garcia@school.edu',
            ],
            [
                'first_name' => 'William',
                'middle_name' => 'Thomas',
                'last_name' => 'Brown',
                'date_of_birth' => '1983-07-09',
                'gender' => 'M',
                'nationality' => 'American',
                'joining_date' => '2023-09-03',
                'employee_id' => 'EMP-SEC-009',
                'shift' => 'Night',
                'position' => 'Security Officer',
                'address_line1' => '369 Guardian Grove',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62709',
                'country' => 'USA',
                'home_phone' => '+1-217-555-2901',
                'mobile_phone' => '+1-217-555-2902',
                'email' => 'william.brown@school.edu',
            ],
            [
                'first_name' => 'Patricia',
                'middle_name' => 'Lynn',
                'last_name' => 'Wilson',
                'date_of_birth' => '1991-10-28',
                'gender' => 'F',
                'nationality' => 'American',
                'joining_date' => '2023-10-12',
                'employee_id' => 'EMP-SEC-010',
                'shift' => 'Morning',
                'position' => 'Security Guard',
                'address_line1' => '741 Shield Circle',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62710',
                'country' => 'USA',
                'home_phone' => '+1-217-555-3001',
                'mobile_phone' => '+1-217-555-3002',
                'email' => 'patricia.wilson@school.edu',
            ],
        ];

        foreach ($securityStaff as $index => $staffData) {
            // Create user account for security staff
            $user = User::create([
                'name' => $staffData['first_name'].' '.$staffData['last_name'],
                'email' => $staffData['email'],
                'password' => Hash::make('security123'), // Default password
                'email_verified_at' => now(),
            ]);

            // Assign security role
            $user->assignRole('Security');

            // Generate unique security code for seeding
            $year = substr($staffData['joining_date'], 0, 4); // Extract year from joining_date
            $securityCode = 'SEC'.$year.str_pad($index + 1, 4, '0', STR_PAD_LEFT);

            // Create security staff record
            $security = SecurityStaff::create([
                'user_id' => $user->id,
                'security_code' => $securityCode,
                'first_name' => $staffData['first_name'],
                'middle_name' => $staffData['middle_name'],
                'last_name' => $staffData['last_name'],
                'date_of_birth' => $staffData['date_of_birth'],
                'gender' => $staffData['gender'],
                'nationality' => $staffData['nationality'],
                'joining_date' => $staffData['joining_date'],
                'employee_id' => $staffData['employee_id'],
                'shift' => $staffData['shift'],
                'position' => $staffData['position'],
                'is_active' => true,
                'address_line1' => $staffData['address_line1'],
                'address_line2' => $staffData['address_line2'] ?? null,
                'city' => $staffData['city'],
                'state' => $staffData['state'],
                'postal_code' => $staffData['postal_code'],
                'country' => $staffData['country'],
                'home_phone' => $staffData['home_phone'],
                'mobile_phone' => $staffData['mobile_phone'],
                'email' => $staffData['email'],
            ]);

            $this->command->info("Created security staff: {$security->full_name} ({$security->security_code})");
        }
    }
}
