<?php

namespace Database\Seeders;

use App\Models\Subject;
use App\Models\Teacher;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teachers = [
            [
                'first_name' => 'Emily',
                'middle_name' => 'Catherine',
                'last_name' => 'Parker',
                'date_of_birth' => '1985-09-15',
                'gender' => 'F',
                'nationality' => 'American',
                'qualification' => 'Bachelor of Education, Master of Arts in Elementary Education',
                'specialization' => 'Mathematics',
                'experience_years' => 8.5,
                'joining_date' => '2022-08-15',
                'employee_id' => 'EMP-TEA-001',
                'teaching_level' => 'Primary',
                'address_line1' => '123 Teacher Lane',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62701',
                'country' => 'USA',
                'home_phone' => '+1-217-555-3101',
                'mobile_phone' => '+1-217-555-3102',
                'email' => 'emily.parker@school.edu',
                'subjects' => ['Mathematics'],
            ],
            [
                'first_name' => 'Jonathan',
                'middle_name' => 'Michael',
                'last_name' => 'Stevens',
                'date_of_birth' => '1982-04-22',
                'gender' => 'M',
                'nationality' => 'American',
                'qualification' => 'Bachelor of Arts in English, Master of Education',
                'specialization' => 'English Language Arts',
                'experience_years' => 12.0,
                'joining_date' => '2021-08-20',
                'employee_id' => 'EMP-TEA-002',
                'teaching_level' => 'Primary',
                'address_line1' => '456 Education Drive',
                'address_line2' => 'Apt 5C',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62702',
                'country' => 'USA',
                'home_phone' => '+1-217-555-3201',
                'mobile_phone' => '+1-217-555-3202',
                'email' => 'jonathan.stevens@school.edu',
                'subjects' => ['English Language Arts', 'Library Skills'],
            ],
            [
                'first_name' => 'Sarah',
                'middle_name' => 'Nicole',
                'last_name' => 'Martinez',
                'date_of_birth' => '1988-12-08',
                'gender' => 'F',
                'nationality' => 'American',
                'qualification' => 'Bachelor of Science in Biology, Teaching Certificate',
                'specialization' => 'Science',
                'experience_years' => 6.0,
                'joining_date' => '2023-01-10',
                'employee_id' => 'EMP-TEA-003',
                'teaching_level' => 'Secondary',
                'address_line1' => '789 Science Street',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62703',
                'country' => 'USA',
                'home_phone' => '+1-217-555-3301',
                'mobile_phone' => '+1-217-555-3302',
                'email' => 'sarah.martinez@school.edu',
                'subjects' => ['Science'],
            ],
            [
                'first_name' => 'Robert',
                'middle_name' => 'James',
                'last_name' => 'Thompson',
                'date_of_birth' => '1980-07-14',
                'gender' => 'M',
                'nationality' => 'American',
                'qualification' => 'Bachelor of Arts in History, Master of Education',
                'specialization' => 'Social Studies',
                'experience_years' => 15.5,
                'joining_date' => '2020-08-25',
                'employee_id' => 'EMP-TEA-004',
                'teaching_level' => 'Secondary',
                'address_line1' => '321 History Boulevard',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62704',
                'country' => 'USA',
                'home_phone' => '+1-217-555-3401',
                'mobile_phone' => '+1-217-555-3402',
                'email' => 'robert.thompson@school.edu',
                'subjects' => ['Social Studies'],
            ],
            [
                'first_name' => 'Angela',
                'middle_name' => 'Marie',
                'last_name' => 'Wilson',
                'date_of_birth' => '1987-03-28',
                'gender' => 'F',
                'nationality' => 'American',
                'qualification' => 'Bachelor of Fine Arts, Teaching Certificate',
                'specialization' => 'Visual Arts',
                'experience_years' => 7.5,
                'joining_date' => '2022-09-05',
                'employee_id' => 'EMP-TEA-005',
                'teaching_level' => 'Primary',
                'address_line1' => '654 Arts Avenue',
                'address_line2' => 'Studio 2B',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62705',
                'country' => 'USA',
                'home_phone' => '+1-217-555-3501',
                'mobile_phone' => '+1-217-555-3502',
                'email' => 'angela.wilson@school.edu',
                'subjects' => ['Visual Arts'],
            ],
            [
                'first_name' => 'David',
                'middle_name' => 'Alexander',
                'last_name' => 'Brown',
                'date_of_birth' => '1984-11-12',
                'gender' => 'M',
                'nationality' => 'American',
                'qualification' => 'Bachelor of Music Education, Master of Arts in Music',
                'specialization' => 'Music',
                'experience_years' => 9.0,
                'joining_date' => '2021-08-30',
                'employee_id' => 'EMP-TEA-006',
                'teaching_level' => 'Primary',
                'address_line1' => '987 Melody Lane',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62706',
                'country' => 'USA',
                'home_phone' => '+1-217-555-3601',
                'mobile_phone' => '+1-217-555-3602',
                'email' => 'david.brown@school.edu',
                'subjects' => ['Music'],
            ],
            [
                'first_name' => 'Michelle',
                'middle_name' => 'Rebecca',
                'last_name' => 'Davis',
                'date_of_birth' => '1986-06-19',
                'gender' => 'F',
                'nationality' => 'American',
                'qualification' => 'Bachelor of Science in Kinesiology, Teaching Certificate',
                'specialization' => 'Physical Education',
                'experience_years' => 8.0,
                'joining_date' => '2022-07-15',
                'employee_id' => 'EMP-TEA-007',
                'teaching_level' => 'Secondary',
                'address_line1' => '147 Fitness Road',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62707',
                'country' => 'USA',
                'home_phone' => '+1-217-555-3701',
                'mobile_phone' => '+1-217-555-3702',
                'email' => 'michelle.davis@school.edu',
                'subjects' => ['Physical Education'],
            ],
            [
                'first_name' => 'Carlos',
                'middle_name' => 'Eduardo',
                'last_name' => 'Rodriguez',
                'date_of_birth' => '1983-02-25',
                'gender' => 'M',
                'nationality' => 'American',
                'qualification' => 'Bachelor of Arts in Spanish Literature, Teaching Certificate',
                'specialization' => 'Spanish Language',
                'experience_years' => 11.0,
                'joining_date' => '2020-08-12',
                'employee_id' => 'EMP-TEA-008',
                'teaching_level' => 'Secondary',
                'address_line1' => '258 Language Circle',
                'address_line2' => 'Building A',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62708',
                'country' => 'USA',
                'home_phone' => '+1-217-555-3801',
                'mobile_phone' => '+1-217-555-3802',
                'email' => 'carlos.rodriguez@school.edu',
                'subjects' => ['Spanish Language'],
            ],
            [
                'first_name' => 'Lisa',
                'middle_name' => 'Ann',
                'last_name' => 'Garcia',
                'date_of_birth' => '1989-10-03',
                'gender' => 'F',
                'nationality' => 'American',
                'qualification' => 'Bachelor of Science in Computer Science, Teaching Certificate',
                'specialization' => 'Technology Education',
                'experience_years' => 5.5,
                'joining_date' => '2023-08-20',
                'employee_id' => 'EMP-TEA-009',
                'teaching_level' => 'A/L-Technology',
                'address_line1' => '369 Technology Way',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62709',
                'country' => 'USA',
                'home_phone' => '+1-217-555-3901',
                'mobile_phone' => '+1-217-555-3902',
                'email' => 'lisa.garcia@school.edu',
                'subjects' => ['Technology Education'],
            ],
            [
                'first_name' => 'Jennifer',
                'middle_name' => 'Louise',
                'last_name' => 'Taylor',
                'date_of_birth' => '1981-08-17',
                'gender' => 'F',
                'nationality' => 'American',
                'qualification' => 'Bachelor of Education, Master of Library Science',
                'specialization' => 'Library Science',
                'experience_years' => 13.0,
                'joining_date' => '2019-08-26',
                'employee_id' => 'EMP-TEA-010',
                'teaching_level' => 'Primary',
                'address_line1' => '741 Knowledge Street',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'postal_code' => '62710',
                'country' => 'USA',
                'home_phone' => '+1-217-555-4001',
                'mobile_phone' => '+1-217-555-4002',
                'email' => 'jennifer.taylor@school.edu',
                'subjects' => ['Library Skills', 'English Language Arts'],
            ],
        ];

        foreach ($teachers as $teacherData) {
            // Create user account for teacher
            $user = User::create([
                'name' => $teacherData['first_name'] . ' ' . $teacherData['last_name'],
                'email' => $teacherData['email'],
                'password' => Hash::make('teacher123'), // Default password
                'email_verified_at' => now(),
            ]);

            // Assign teacher role
            $user->assignRole('Teacher');

            // Create teacher record
            $teacher = Teacher::create([
                'user_id' => $user->id,
                'teacher_code' => Teacher::generateTeacherCode(),
                'first_name' => $teacherData['first_name'],
                'middle_name' => $teacherData['middle_name'],
                'last_name' => $teacherData['last_name'],
                'date_of_birth' => $teacherData['date_of_birth'],
                'gender' => $teacherData['gender'],
                'nationality' => $teacherData['nationality'],
                'qualification' => $teacherData['qualification'],
                'specialization' => $teacherData['specialization'],
                'experience_years' => $teacherData['experience_years'],
                'joining_date' => $teacherData['joining_date'],
                'employee_id' => $teacherData['employee_id'],
                'is_active' => true,
                'address_line1' => $teacherData['address_line1'],
                'address_line2' => $teacherData['address_line2'] ?? null,
                'city' => $teacherData['city'],
                'state' => $teacherData['state'],
                'postal_code' => $teacherData['postal_code'],
                'country' => $teacherData['country'],
                'home_phone' => $teacherData['home_phone'],
                'mobile_phone' => $teacherData['mobile_phone'],
                'email' => $teacherData['email'],
            ]);

            // Attach subjects to teacher
            foreach ($teacherData['subjects'] as $subjectName) {
                $subject = Subject::where('subject_name', $subjectName)->first();
                if ($subject) {
                    $teacher->subjects()->attach($subject->id);
                }
            }

            $this->command->info("Created teacher: {$teacher->full_name} ({$teacher->teacher_code}) - Subjects: " . implode(', ', $teacherData['subjects']));
        }
    }
}
